### ISSUE TITLE
Redis failures

### ISSUE THREAD

**Issue by soatok** [badges/poser#29]
https://poser.pugx.org/soatok/faq-off/v/stable yields the following:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="1908" height="20">
    <linearGradient id="b" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
    </linearGradient>
    <mask id="a">
        <rect width="1908" height="20" rx="3" fill="#fff"/>
    </mask>
    <g mask="url(#a)">
        <rect width="1855" height="20" fill="#555"/>
        <rect x="1855" width="53" height="20" fill="#e05d44"/>
        <rect width="1908" height="20" fill="url(#b)"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="928.5" y="15" fill="#010101" fill-opacity=".3">exception 'Predis\ServerException' with message 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.' in /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php:282
Stack trace:
#0 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(250): Predis\Client->onResponseError(Object(Predis\Command\StringIncrement), Object(Predis\ResponseError))
#1 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client->executeCommand(Object(Predis\Command\StringIncrement))
#2 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client-> call('incr', Array)
#3 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client->incr('STAT.TOTAL')
#4 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(75): PUGX\StatsBundle\Service\RedisPersister->incrementTotalAccess()
#5 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(45): PUGX\StatsBundle\Listener\StatsListener->persistData(Object(Symfony\Component\HttpFoundation\Request), 'versionAction')
#6 [internal function]: PUGX\StatsBundle\Listener\StatsListener->onKernelController(Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1782): call user func(Array, Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1700): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#9 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3208): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#10 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3173): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3324): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/bp/badge-poser3/app/bootstrap.php.cache(2514): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/bp/badge-poser3/web/app.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}</text>
        <text x="928.5" y="14">exception 'Predis\ServerException' with message 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.' in /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php:282
Stack trace:
#0 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(250): Predis\Client->onResponseError(Object(Predis\Command\StringIncrement), Object(Predis\ResponseError))
#1 /var/www/bp/badge-poser3/vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client->executeCommand(Object(Predis\Command\StringIncrement))
#2 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client-> call('incr', Array)
#3 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Service/RedisPersister.php(62): Predis\Client->incr('STAT.TOTAL')
#4 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(75): PUGX\StatsBundle\Service\RedisPersister->incrementTotalAccess()
#5 /var/www/bp/badge-poser3/src/PUGX/StatsBundle/Listener/StatsListener.php(45): PUGX\StatsBundle\Listener\StatsListener->persistData(Object(Symfony\Component\HttpFoundation\Request), 'versionAction')
#6 [internal function]: PUGX\StatsBundle\Listener\StatsListener->onKernelController(Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1782): call user func(Array, Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/bp/badge-poser3/app/cache/prod/classes.php(1700): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#9 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3208): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.controll...', Object(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#10 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3173): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/bp/badge-poser3/app/bootstrap.php.cache(3324): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/bp/badge-poser3/app/bootstrap.php.cache(2514): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/bp/badge-poser3/web/app.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}</text>
        <text x="1880.5" y="15" fill="#010101" fill-opacity=".3">generic</text>
        <text x="1880.5" y="14">generic</text>
    </g>
</svg>

```

**Comment by garak** [comment]
Maybe this issue should be opened on https://github.com/PUGX/badge-poser

**Comment by JellyBellyDev** [comment]
The problem no longer seems present to me!
